# Generated by Django 6.1.1 on 2026-09-19 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostagemMural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Card')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('cor_fundo', models.CharField(choices=[('#E3F2FD', 'Azul Suave'), ('#E8F5E9', 'Verde Suave'), ('#FFFDE7', 'Amarelo Suave'), ('#FFEBEE', 'Vermelho Suave'), ('#F3E5F5', 'Roxo Suave')], default='#E3F2FD', max_length=7, verbose_name='Cor do Card')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Postagem do Mural',
                'verbose_name_plural': 'Postagens do Mural',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
